Separate error output
weirdan/codeception-psalm-module pull request #45
Opened 2023-01-19 04:13 UTC by jack-worman

Fix for: https://github.com/vimeo/psalm/issues/9034

stdout and stderr are now saved separately

2023-01-20 21:23 UTC, jack-worman commented
@weirdan Is this an acceptable solution?

2023-01-20 21:48 UTC, weirdan commented
There's nothing wrong with the solution itself, except it would require upgrading the module for all packages that depend on it. I plan to work on the solution that won't require it in the Psalm repo later today.

2023-01-23 07:16 UTC, weirdan commented
> I plan to work on the solution that won't require it in the Psalm repo later today.

Done.

2023-01-23 07:20 UTC, weirdan requested changes

2023-01-23 07:20 UTC, weirdan commented on src/Module.php
> +        $this->errorOutput = $process->getErrorOutput();
It needs to be output, e.g. via `$this->debug`. Otherwise, it's not too useful.

2025-02-07 03:32 UTC, closed without merging